apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000        # Puerto del servicio dentro del cluster
      targetPort: 3000  # Puerto del contenedor
      nodePort: 30001   # Puerto expuesto en tu máquina